title: UH-Clubr
description: The complete club directory for students at the University of Hawaii at Manoa
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
